Addition of separate namespaces for agents example
cloudbees/cloudbees-examples pull request #31
Opened 2020-12-16 17:25 UTC by stephankfolkes

This is a snippet of the yaml file, and it shows agent options and configuration that can enable separate namespaces for agents.

2020-12-16 22:52 UTC, pattyhair requested changes
This file must be placed in the `cloudbees-ci ` area of the repo.  In fact, that entire folder ,`helm-custom-value-file-examples`, must be moved to `cloudbees-ci` folder.  Please rework your PR (and optionally move the helm folder.

2020-12-17 08:48 UTC, danieloa commented
I understand the importance of having these values documented somewhere, however, that snippet of code comes from extracting the values.yaml file from the helm release. thus, anyone can get those values by running `helm fetch cloudbees/cloudbees-core --untar | cat cloudbees-core/values.yaml`

2020-12-17 14:42 UTC, Vlatombe commented
I think these examples should be removed. The reference is the product documentation.

Values are fully documented -- https://artifacthub.io/packages/helm/cloudbees/cloudbees-core or using the command @danieloa mentioned.

2020-12-17 14:44 UTC, kyounger commented
Or even better: `helm show values cloudbees/cloudbees-core`

2020-12-17 17:27 UTC, closed without merging